version: '3'

volumes:
  production_django_media: {}
  production_django_logs: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: televi1_production_django
    volumes:
      - production_django_media:/app/televi1/media
      - production_django_logs:/app/televi1/logs
    depends_on:
      - redis
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    command: /start
    extra_hosts:
      - 'host-gateway:host-gateway'

  telegrampoll:
    <<: *django
    image: televi1_production_telegrampoll
    command: /start-telegrampoll

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: televi1_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: televi1_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: televi1_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: televi1_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - '0.0.0.0:80:80'
