# Generated by Django 4.2.13 on 2024-07-20 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tid', models.BigIntegerField()),
                ('tusername', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=63)),
                ('api_token', models.CharField(max_length=127)),
                ('secret_token', models.CharField(max_length=255)),
                ('url_specifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('is_master', models.BooleanField()),
                ('webhook_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_powered_off', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_id', models.CharField(max_length=255)),
                ('file_unique_id', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tid', models.IntegerField(db_comment='id of message in telegram server', unique=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('voice', 'Voice')], max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('media_group_id', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramMessageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mention', 'Mention'), ('hashtag', 'Hashtag'), ('cashtag', 'Cachtag'), ('bot_command', 'Bot Command'), ('url', 'Url'), ('email', 'Email'), ('phone_number', 'Phone Number'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('spoiler', 'Spoiler'), ('blockquote', 'Blockquote'), ('expandable_blockquote', 'Expandable Blockquote'), ('code', 'Code'), ('pre', 'Pre'), ('text_link', 'Text Link'), ('text_mention', 'Text Mention'), ('custom_emoji', 'Custom Emoji')], max_length=31)),
                ('offset', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127)),
                ('must_join_chat_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUploaderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
