# Generated by Django 4.2.13 on 2024-07-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import televi1.telegram_bot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0001_initial'),
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAudio',
            fields=[
                ('telegramfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.telegramfile')),
                ('duration', models.IntegerField()),
                ('performer', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.telegramfile',),
        ),
        migrations.CreateModel(
            name='TelegramDocument',
            fields=[
                ('telegramfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.telegramfile')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.telegramfile',),
        ),
        migrations.CreateModel(
            name='TelegramPhotoSize',
            fields=[
                ('telegramfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.telegramfile')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.telegramfile',),
        ),
        migrations.CreateModel(
            name='TelegramVoice',
            fields=[
                ('telegramfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.telegramfile')),
                ('duration', models.IntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.telegramfile',),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_tid', models.BigIntegerField(db_comment='user id in telegram')),
                ('tbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegramuserprofiles', to='telegram_bot.telegrambot')),
            ],
            bases=('users.user', models.Model),
            managers=[
                ('objects', televi1.telegram_bot.models.TelegramUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='telegramuploadermessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='telegram_bot.telegrammessage'),
        ),
        migrations.AddField(
            model_name='telegramuploadermessage',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='telegram_bot.telegramuploader'),
        ),
        migrations.AddField(
            model_name='telegramuploader',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegramuploaders_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramuploader',
            name='messages',
            field=models.ManyToManyField(related_name='telegramuploaders', through='telegram_bot.TelegramUploaderMessage', to='telegram_bot.telegrammessage'),
        ),
        migrations.AddField(
            model_name='telegrammessageentity',
            name='telegram_message_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caption_entities', to='telegram_bot.telegrammessage'),
        ),
        migrations.AddField(
            model_name='telegrammessageentity',
            name='telegram_message_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_entities', to='telegram_bot.telegrammessage'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages', to='telegram_bot.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages_sentby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramfile',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_files', to='telegram_bot.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegramfile',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrambots_addedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='added_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrambots_addedfrom', to='telegram_bot.telegrambot'),
        ),
        migrations.CreateModel(
            name='TelegramVideo',
            fields=[
                ('telegramfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.telegramfile')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegramvideo', to='telegram_bot.telegramphotosize')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.telegramfile',),
        ),
        migrations.AddConstraint(
            model_name='telegramuser',
            constraint=models.UniqueConstraint(fields=('user_tid', 'tbot'), name='unique_tuser_tbot'),
        ),
        migrations.AddConstraint(
            model_name='telegrammessageentity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('telegram_message_caption__isnull', False), ('telegram_message_text__isnull', True)), models.Q(('telegram_message_caption__isnull', True), ('telegram_message_text__isnull', False)), _connector='OR'), name='either_text_or_caption_entity'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages', to='telegram_bot.telegramaudio'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages', to='telegram_bot.telegramdocument'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='photo',
            field=models.ManyToManyField(related_name='telegrammessages', to='telegram_bot.telegramphotosize'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages', to='telegram_bot.telegramvideo'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegrammessages', to='telegram_bot.telegramvoice'),
        ),
        migrations.AddConstraint(
            model_name='telegramfile',
            constraint=models.UniqueConstraint(fields=('file_id', 'file_unique_id'), name='unique_file'),
        ),
        migrations.AddField(
            model_name='telegramdocument',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegramdocument', to='telegram_bot.telegramphotosize'),
        ),
        migrations.AddField(
            model_name='telegramaudio',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegramaudio', to='telegram_bot.telegramphotosize'),
        ),
    ]
