# Generated by Django 4.2.13 on 2024-07-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('telegram_bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='telegramuploader',
            name='tbot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='uploaders', to='telegram_bot.telegrambot'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatJoinUploaderCondition',
            fields=[
                ('uploadercondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_bot.uploadercondition')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_bot.uploadercondition',),
        ),
        migrations.CreateModel(
            name='UploaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queryid', models.CharField(max_length=5)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaderlinks', to='telegram_bot.telegramuploader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
