# Generated by Django 4.2.13 on 2024-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_uploadercondition_telegramuploader_tbot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadercondition',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='uploaderlink',
            name='queryid',
            field=models.CharField(db_index=True, max_length=31),
        ),
        migrations.DeleteModel(
            name='ChatJoinUploaderCondition',
        ),
        migrations.DeleteModel(
            name='UploaderCondition',
        ),
    ]
